### ISSUE TITLE
Format settings, GOP in mediainfo

### ISSUE THREAD

**Issue by sannies** [justdan96/tsMuxer#239]
Hi,
I'm trying to generate a very specific format for a hardware decoder. The manufacturer tells me that he suspects it's not playing cause my TS file doesn't  show
`Format settings, GOP                     : M=4, N=12`
in mediainfo. My input MP4 shows exactly those Format settings, GOP value but after muxing via 

```
MUXOPT --cbr --vbv-len=500 --bitrate=2000
V_MPEG-2, TOS_35M2_FW29_mp2js_Eng.mp4, pid=0x31, track=1
A_MP3, TOS_35M2_FW29_mp2js_Eng.mp4, pid=0x42, track=2
```
(I'm currently on a locally patched version with https://github.com/justdan96/tsMuxer/pull/74 I can therefore set pids)

it shows as 
`Format settings, GOP                     : Variable`

Not sure if I'd label this as a bug but it's awkward in my eyes. Perhaps you guys can give me a hint were to start looking or already now the reason - I wasn't even able to find out how mediainfo gets that value. 

Source file here: https://we.tl/t-sUFOlhGD1q

**Comment by justdan96** [comment]
I'll wait for others to weigh in on some of your points but for now I'll say the following command should show GOP values for all frames in a file, might be useful to check:

```
ffprobe -show_frames /(path to the file) | grep pict_type
```
As variable GOP isn't that unusual from what I've read maybe it would be good to know if the hardware can handle variable GOP generally.

**Comment by sannies** [comment]
Thanks for your response. 
I got 1759 repetitions of the pattern:
```
pict_type=I
pict_type=B
pict_type=B
pict_type=B
pict_type=P
pict_type=B
pict_type=B
pict_type=B
pict_type=P
pict_type=B
pict_type=B
pict_type=B
```

in the file. At the end the pattern is obviously not complete as the frame count is not divisible by 12. 

The hardware is a 20 year old screen in the backrest of an airplane. It's hard to get the specifics besides of what has been written down (in the confidential specs). I fear I must deliver what the manufacturer is asking for. 

I'm wondering how this `Format settings, GOP : Variable` vs `M=4, N=12` is detected. Is there a flag in the TS to signal a fixed GOP structure?

**Comment by justdan96** [comment]
I guess the sequence is supposed to be: 
`I BBBP - I BBBP - I BBBP - I BBBP - I BBBP - I BBBP`

You may want to post on the [tsMuxer Doom9 thread](https://forum.doom9.org/showthread.php?t=176668), someone from that community may be able to help you with your question as I fear I just don't know enough about how the GOP is defined.

**Comment by sannies** [comment]
The sequence is as it is supposed to be. Every 4th frame is a P, Every 12th frame an I. I just need this info conveyed in the MPEG2TS.
I'll post in the doom9 thread in 5 days when my waiting period is over (am I trying to buy a gun?)

**Comment by jcdr428** [comment]
@sannies could you please post a link to a TS correctly showing the GOP : M=4, N=12 in mediainfo, for analysis / comparison.

**Comment by justdan96** [comment]
#245 has now been merged

**Comment by sannies** [comment]
Thank you for the heads up. It still doesn't show the "Format settings, GOP" correctly. I'm doing my best to get an example stream that shows M4 N12  but so far no luck. I only got a mediainfo screenshot :( as the content showing M4 N12 is production content. 

I browsed some specs and to me it looks like this info is might be conveyed via the "IBP descriptor". I must admit that I'm completely clueless in regards to TS but I'm learning

I do believe that the 'descriptors' are the solution but my source MP4 might have the descriptors in the 'mp4v/esds' atom.

**Comment by sannies** [comment]
Ok, I found an example. I got an m2v with M3N15 and that gets muxed into a TS retaining the fixed GOP information. 
```

MUXOPT --cbr --vbv-len=1000 --bitrate=4000
V_MPEG-2, MainconceptLogo_MPEG2_ES_720x576.m2v, track=1
```

[example-M3N15.zip](https://github.com/justdan96/tsMuxer/files/4338342/example-M3N15.zip)

**Comment by jcdr428** [comment]
@sannies have you tested the file output from today's bintray version (with the new m2ts descriptor) on the hardware ?

**Comment by sannies** [comment]
Thank you for your support and your open ears.  I will close the ticket as I managed to get this M4 N12 info into the TS. I used ffmpeg to produce a raw m2v file like this and when packaged into a TS the info is corrected conveyed.

`ffmpeg -y -i input.mp4 -t 20 -c:v mpeg2video -profile:v 4 -level:v 8 -g 12 -bf 3 -flags +cgop -mpv_flags +strict_gop -pix_fmt yuv420p -b_strategy 0 -b:v 1500k -bufsize 229376.0 -minrate 1500k -maxrate 1500k -sc_threshold 1000000000  output.m2v`

[output.m2v in ZIP](https://github.com/justdan96/tsMuxer/files/4342382/TOS_35M2_FW29_mp2js_Eng-nl8vFHTvuI7.m2v.zip)

I didn't go to the bottom and won't go there. I can just say: this works and I'll this info here for next one running into a similar issue.

**Comment by justdan96** [comment]
@jcdr428 I'm still not sure how to categorise the issue - do you think it's a bug on our side or that an enhancement would be required to enable these settings?

**Comment by sannies** [comment]
There are a few scenarios:

- It might be an issue on your side if we assume that the info is in the MP4 file but then not conveyed into the TS.
- It might be a mediainfo issue where mediainfo doesn't recognize fixed GOP structure when e.g. the last frame in a GOP is a B frame.
- But might also be a specification edge case where the fixed/variable GOP thing is defined slightly different in MP4 and TS.  

Reading MPEG2 specs causes dizziness. That makes it hard to find out.

**Comment by jcdr428** [comment]
@sannies @justdan96 I don't believe that there is a bug in tsMuxer. The TOS m4v sample is definitely a variable GOP, this can be seen with ffprobe command line given above (see for example pictures 266, 267, 268 between two I-frames), or in the attached file.

The mpeg2 descriptor I've added is an HDMV descriptor, so it should work as long as framerate/(p or i) is Blu-ray compliant. When I have time I will add the standard 0x02 video descriptor for non-compliant e.g. 29.97p.

@sannies please confirm that the issue can be closed, thanks.

[GOP - TOS_35M2_FW29_mp2js_Eng.txt](https://github.com/justdan96/tsMuxer/files/4345583/GOP.-.TOS_35M2_FW29_mp2js_Eng.txt)
