### ISSUE TITLE
Bitstream exception std::exception.

### ISSUE THREAD

**Issue by razierklinge** [justdan96/tsMuxer#608]
I have a Dolby Vision file I'm trying to convert from profile 8 to profile 7. When I try to load it into the latest nightly of the GUI, nothing happens, it doesnt get loaded to the list of input files and no error is thrown. 

If I try to use the commandline with a meta file I see:
`HEVC muxing fps is not set. Get fps from stream. Value: 23.976`
`Bitstream exception std::exception. It does not have to be! Please contact application support team for more information.`

I switched to commit aa26bf07f45d30940adb35f2086b695c00a5d85e and the file can be loaded into the GUI, and also is accepted in the commandline. However I then get:
`99.8% complete`
`Not enough buffer for parse video stream. Current frame num 173132`

So it looks like the Bitstream error originates in aac7d2b26cbfd727b0f59d04eb41b07a950f1859.

**Comment by jcdr428** [comment]
@razierklinge can I please have a sample of the m2ts provoking the bug ?

**Comment by razierklinge** [comment]
I gotta be honest, I'm not well versed in the area of video editing. What would be the easiest way to make a small sample? The original file is a ~40GB mkv file. And I'm assuming getting the end of the file would be best?

**Comment by jcdr428** [comment]
@razierklinge there was indeed a mistake in my commit aac7d2b . I've pushed a correction, please try tomorrow's release.

**Comment by razierklinge** [comment]
@jcdr428 I pulled your fixes and it did get rid of the Bitstream exception. However I'm still getting the error "Not enough buffer for parse video stream." at the end of muxing. It seems to be happening on the very last frame of my file.

**Comment by jcdr428** [comment]
@razierklinge can you please try some previous versions to see whether you are getting the same "Not enough buffer for parse video stream" message ?

**Comment by razierklinge** [comment]
I went tried many different versions hopping back from version to version and all gave the same error on the last frame of the file.

**Comment by jcdr428** [comment]
@razierklinge I can't solve without the sample.
For instance you can use MkvToolNix-Gui, Output tab->split mode "after output duration" 7100s, check that the second output  mkv still produces the bug in tsMuxer, and share this second mkv.

**Comment by jcdr428** [comment]
@razierklinge can you please provide the sample.

**Comment by jcdr428** [comment]
No sample provided, closing. Can be reopened upon request.
