### ISSUE TITLE
E-AC3 Playback Sound Problem in HW players & Sw Players (PDVD) !

### ISSUE THREAD

**Issue by metagondria** [justdan96/tsMuxer#803]
Hello

I want to report and bring the following issue to the developers attention . because it has been an pita for an long time now!

An issue that persists up to release → Nightly build from 2023-10-25-01-53-22 !

So, in a nutshell, when i create media files containing E-AC3 tracks, PDVD & HW bbluray player throws Unknow format for audio error, as a result i don't have SOUND during playback.

Now, i managed to work arround this by going back to official release of TSmuxer 2.16.x ..  
The media file plays just fine again in all players by doing that.

BUT... the downsize is that the older release of TSmuxer, now has problems Demux/extract and/or muxing the newer TRUEHD ATMOS Tracks.

Crashes happen when Hybrid tries to extract/mux Atmos tracks from files !
But the weird thing is, when using TSmuxer outside of hybrid with the gui..  Extraction / muxing of Atmos tracks succeeds !?!?

Fyi, iam mainly using Hybrid to batch process files.  software created by Selur [https://forum.selur.net/forum-3.html](url) 

Cheers,

**Comment by DreckSoft** [comment]
Strange, that should have been fixed in this issue: #682

**Comment by metagondria** [comment]
@ drecksoft

Thanks for your input.. and link ..

some in that link mentioned it still doesn't work with nightly builds... 
And the issue happends to be with nightly builds !!

So... i'll give 1.10.6 a try if i can still find it..

**Comment by jcdr428** [comment]
@metagondria can you please provide a (small) m2ts from a tsMuxer version that works, and the m2ts from the latest nightly, so I can analyse differences ?

**Comment by metagondria** [comment]
> @metagondria can you please provide a (small) m2ts from a tsMuxer version that works, and the m2ts from the latest nightly, so I can analyse differences ?

Sure.. here's the [LINK](https://forum.selur.net/attachment.php?aid=2105) to the bad m2ts file created with tsmux nightly

And the [LINK ](https://forum.selur.net/attachment.php?aid=2106)to an good working m2ts created by TSmuxer 2.16 

cheers,

**Comment by jcdr428** [comment]
@metagondria what is the source of your tsMuxer 2.16 ? I don't recall having seen any version of tsMuxer producing outputs with a PID n°17 as a first packet, without SIT packets, with "random_access_indicator" in the adaptation field etc. I am surprised that it can be read by a player.

Other than that, the difference seems to be the transport_priority indicator which is set to one for the legacy AC3 packets in the EAC3 stream: this was the purpose of issue #682 highlighted by @DreckSoft.

This is in accordance with the Blu-ray standard:
![image](https://user-images.githubusercontent.com/56721609/227591030-800695c1-b675-4e45-9c2c-cfec81928184.png)

**Comment by metagondria** [comment]
> @metagondria what is the source of your tsMuxer 2.16 ? I don't recall having seen any version of tsMuxer producing outputs with a PID n°17 as a first packet, without SIT packets, with "random_access_indicator" in the adaptation field etc. I am surprised that it can be read by a player.
> 
> Other than that, the difference seems to be the transport_priority indicator which is set to one for the legacy AC3 packets in the EAC3 stream: this was the purpose of issue #682 highlighted by @DreckSoft.
> 
> This is in accordance with the Blu-ray standard: ![image](https://user-images.githubusercontent.com/56721609/227591030-800695c1-b675-4e45-9c2c-cfec81928184.png)

hello again,

The version i have used is rather years old (modified date 2014)..  But is the last official build released by the original developer at that time..

I've have attached an zip file with the tsmuxer that succeeds to mux E-ac3 tracks , but has issues Extracting / muxing Atmos tracks → crashes in hybrid.  

Funny thing is, using 2.16 outside hybrid using gui, can handle most Truehd atmos tracks just fine..
But there are → A_AC3 ← - Atmos tracks aswell nowday's, that gave issues in tsmuxer !

Link to Tsmux ↓

[tsMuxeR.zip](https://github.com/justdan96/tsMuxer/files/13311674/tsMuxeR.zip)

**Comment by jcdr428** [comment]
@metagondria Ok ! this is tsMuxer 2.6.12.

Here is your "bad sample", with only change = all transport_priority changed back to 0: [Test-no-priority.zip](https://github.com/justdan96/tsMuxer/files/13312133/Test-no-priority.zip)

Can you please confirm whether this is working in your player ?

**Comment by metagondria** [comment]
> @metagondria Ok ! this is tsMuxer 2.6.12.
> 
> Here is your "bad sample", with only change = all transport_priority changed back to 0: [Test-no-priority.zip](https://github.com/justdan96/tsMuxer/files/13312133/Test-no-priority.zip)
> 
> Can you please confirm whether this is working in your player ? Edit : what is your HW player brand and model ?

First of, it's very easy to recreate an good example from an bad remuxed file..
I just need to find the → RIGHt ← TSmux release and run the bad *.ts *.mkv or wothever container through that release and remux it to an new media file.   Audio is audiable again lol ..

But as for that sample you've sended me..  Unfortunately , STILL no audio in strict players .. only Video !
I asume you are trying to fix this issue for future nightly builds to come !?



cheers,

**Comment by DreckSoft** [comment]
Btw: My PowerDVD WILL play E-AC3 with the current version of TSMuxer. At least the files I tried. I might check your if I boot up the Windows machine for some reason.

**Comment by metagondria** [comment]
> Btw: My PowerDVD WILL play E-AC3 with the current version of TSMuxer. At least the files I tried. I might check your if I boot up the Windows machine for some reason.

Strange, although iam on pdvd Ultra 22 .. Usually the problematic media file will fail in ANY pdvd releases .. because the issue is related to the media file ofcourse..

Just like an bluray movie or episode stick would give playback problems in pdvd because of corrupt Bluray structure or other thing that might have gone bad during rip process / or disc read .. you know..

Anyway, i hope you do progress..

Looking out for an TSmux nightly build that work well with EAC3 and True HD atmos tracks aswell... you know!!
Again, these issue mostly (not all the time) presents itself when i process an media file through Hybrid (Selur soft).. 


cheers,
TD

**Comment by jcdr428** [comment]
> > Edit : what is your HW player brand and model ?

> Anyway, i hope you do progress..

Little progress: we now know it does not come from transport priority.
@DreckSoft is the "bad sample" playing on your Panasonic standalone player ?

**Comment by metagondria** [comment]
> > > Edit : what is your HW player brand and model ?
> 
> > Anyway, i hope you do progress..
> 
> Little progress: we now know it does not come from transport priority. @DreckSoft is the "bad sample" playing on your Panasonic standalone player ?

My hardware player is an Sony buray is a simple 1080p player (no 4K), Model BDP-S4500, and is up to date with last software / firmware.

Anyway, don't actually need hw player to reproduce the issue, because a strict software player like PDVD is very close to emulate HW player , like when it fails in my HWplayer the content sure will fail for like 99% i pdvd (not always though) ..

That's what i actually mean by strict as in strict DVD/BD compliant standards.

goot to know you make progress;

cheers

**Comment by jcdr428** [comment]
OK, so that bug was coming from commit 4832f9f and issue #694.
I have pushed a fix for the next nightly - @moveman, please take note of the fix: streamType remains 0x84 (not 0x87) for m2ts files.

**Comment by donnafaye0323** [comment]
> OK, so that bug was coming from commit [4832f9f](https://github.com/justdan96/tsMuxer/commit/4832f9f4e8364f402e63a6e654629627276e7755) and issue #694. I have pushed a fix for the next nightly.
> 
> @moveman, please take note of the fix: streamType remains 0x84 for m2ts files. Only .ts files can have 0x87 / EAC3_ATSC stream type.

@jcdr428
You are right. Only Blu-Ray videos and PVR recordings have .AC3 audio and .MTS and .TS video formats.

**Comment by metagondria** [comment]
> > OK, so that bug was coming from commit [4832f9f](https://github.com/justdan96/tsMuxer/commit/4832f9f4e8364f402e63a6e654629627276e7755) and issue #694. I have pushed a fix for the next nightly.
> > @moveman, please take note of the fix: streamType remains 0x84 for m2ts files. Only .ts files can have 0x87 / EAC3_ATSC stream type.
> 
> @jcdr428 You are right. Only Blu-Ray videos and PVR recordings have .AC3 audio and .MTS and .TS video formats.

@donnafay
Say wut ↑ 0_o ? 

@jcdr428 
I want to confirm that it is indeed "fixed" ... for now xD 
Much Obliged jcd

**Comment by jcdr428** [comment]
> but just did an passthrough (extract/remux) with an media file containing an True-HD Atmos track = Extract = V but Crashed at mux stage !!

@metagondria can you please open a separate issue, describing the cause and outcome in a little more detail.
